modLoader="javafml" #mandatory
loaderVersion="[47,)" # Forge 47.x for MC 1.20.1
license="MIT"

[[mods]]
modId="create_train_station_speakers" # must match @Mod annotation
version="1.0.0"
displayName="Create: Train Station Speakers"
authors="RSlover521, PlankPower"
description='''
Adds station speakers that can announce arriving trains with TTS.
'''

[[dependencies.create_train_station_speakers]]
modId="create"
mandatory=true
versionRange="[6.0.8,6.1.0)"
ordering="NONE"
side="BOTH"

[[dependencies.create_train_station_speakers]]
modId="railways"
mandatory=true
versionRange="[1.7.2,2.0.0)"
ordering="NONE"
side="BOTH"

[[dependencies.create_train_station_speakers]]
modId="createrailwaysnavigator"
mandatory=true
versionRange="[1.20.1-beta-0.8.5-C6,)"
ordering="NONE"
side="BOTH"
