{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "forgespi",
    "version": "7.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "mergetool",
          "version": {
            "requires": "1.1.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        }
      ],
      "files": [
        {
          "name": "forgespi-7.0.1.jar",
          "url": "forgespi-7.0.1.jar",
          "size": 29831,
          "sha512": "412d3c9c64f8bef21fd2c9677aaf45abfd49aea7c8b494f6fdd78e38c3f252bcb0fe6a4a4f6d1cbe9ed7cdf4f6f814e1e8d0abf55a346fdcf70b8190d0f690f2",
          "sha256": "2298eaba25d066afd9b329de7f75e7bf78ef47f3045e6ecb0e40428d875e4b84",
          "sha1": "3b4972a0cdb135853dba219be61a79b22cff1309",
          "md5": "bd34d20287dc95201fe9475a8bbc2540"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cpw.mods",
          "module": "modlauncher",
          "version": {
            "requires": "9.0.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "cpw.mods",
          "module": "securejarhandler",
          "version": {
            "requires": "0.9.52"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "mergetool",
          "version": {
            "requires": "1.1.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        }
      ],
      "files": [
        {
          "name": "forgespi-7.0.1.jar",
          "url": "forgespi-7.0.1.jar",
          "size": 29831,
          "sha512": "412d3c9c64f8bef21fd2c9677aaf45abfd49aea7c8b494f6fdd78e38c3f252bcb0fe6a4a4f6d1cbe9ed7cdf4f6f814e1e8d0abf55a346fdcf70b8190d0f690f2",
          "sha256": "2298eaba25d066afd9b329de7f75e7bf78ef47f3045e6ecb0e40428d875e4b84",
          "sha1": "3b4972a0cdb135853dba219be61a79b22cff1309",
          "md5": "bd34d20287dc95201fe9475a8bbc2540"
        }
      ]
    }
  ]
}
