{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "srgutils",
    "version": "0.4.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "srgutils-0.4.15.jar",
          "url": "srgutils-0.4.15.jar",
          "size": 69393,
          "sha512": "3ff56c4093f79ec700eb6231bdccebb23401aefd8b5bf08327bbe804a99c075af8926c939aaa11370bfae1271b64be0fb9c0408522f01bbe42262d1d6cebab2e",
          "sha256": "f6bdebb7fae108329acddfc812f237c7f6328a98e3f282a105edfc161d0215e3",
          "sha1": "ca408b131759478f164e010fae0d73997e125fb5",
          "md5": "79812fd073afe1c046bc1ea46ad28095"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "srgutils-0.4.15.jar",
          "url": "srgutils-0.4.15.jar",
          "size": 69393,
          "sha512": "3ff56c4093f79ec700eb6231bdccebb23401aefd8b5bf08327bbe804a99c075af8926c939aaa11370bfae1271b64be0fb9c0408522f01bbe42262d1d6cebab2e",
          "sha256": "f6bdebb7fae108329acddfc812f237c7f6328a98e3f282a105edfc161d0215e3",
          "sha1": "ca408b131759478f164e010fae0d73997e125fb5",
          "md5": "79812fd073afe1c046bc1ea46ad28095"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "srgutils-0.4.15-sources.jar",
          "url": "srgutils-0.4.15-sources.jar",
          "size": 21717,
          "sha512": "c875579758c3b53b5dcc0cfeaf6f18307d601d8a33246e36cf3011502a8b3402c340e24924c0b0ae9ea6608b311691bf7177994e4d74943f153082392cf828ac",
          "sha256": "5f818da28bc414632c0f944667ce4c7aa0e9e0bf8b1c8ee96eef71fd009eccf0",
          "sha1": "e385404e84b778248ec4df7fb1a16934010d4daf",
          "md5": "d6474d66bfd6d469e4f31cd027c99abf"
        }
      ]
    }
  ]
}
